# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='blah'),
            preserve_default=False,
        ),
    ]
