# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commenteds', to='users.User'),
            preserve_default=False,
        ),
    ]
