# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170925_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='I am a person', max_length=255),
            preserve_default=False,
        ),
    ]
